require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/grids", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Grid. As you add validations to Grid, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Grid.create! valid_attributes
      get grids_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      grid = Grid.create! valid_attributes
      get grid_url(grid)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_grid_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      grid = Grid.create! valid_attributes
      get edit_grid_url(grid)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Grid" do
        expect {
          post grids_url, params: { grid: valid_attributes }
        }.to change(Grid, :count).by(1)
      end

      it "redirects to the created grid" do
        post grids_url, params: { grid: valid_attributes }
        expect(response).to redirect_to(grid_url(Grid.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Grid" do
        expect {
          post grids_url, params: { grid: invalid_attributes }
        }.to change(Grid, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post grids_url, params: { grid: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested grid" do
        grid = Grid.create! valid_attributes
        patch grid_url(grid), params: { grid: new_attributes }
        grid.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the grid" do
        grid = Grid.create! valid_attributes
        patch grid_url(grid), params: { grid: new_attributes }
        grid.reload
        expect(response).to redirect_to(grid_url(grid))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        grid = Grid.create! valid_attributes
        patch grid_url(grid), params: { grid: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested grid" do
      grid = Grid.create! valid_attributes
      expect {
        delete grid_url(grid)
      }.to change(Grid, :count).by(-1)
    end

    it "redirects to the grids list" do
      grid = Grid.create! valid_attributes
      delete grid_url(grid)
      expect(response).to redirect_to(grids_url)
    end
  end
end
